# Generated by Django 3.2.9 on 2021-11-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Sex', models.CharField(max_length=1)),
                ('Height', models.IntegerField(blank=True, null=True)),
                ('Weight', models.IntegerField(blank=True, null=True)),
                ('Team', models.CharField(max_length=255)),
                ('NOC', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Games', models.CharField(max_length=255)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Year', models.PositiveIntegerField()),
                ('Season', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Sport', models.CharField(max_length=255)),
                ('Event', models.CharField(max_length=255)),
                ('Medal', models.CharField(max_length=255)),
                ('personal', models.ManyToManyField(to='olimpic.Personal')),
            ],
        ),
    ]
